name: CI/CD Image 2.0

on:
  push:
    branches:
      - dev
    paths-ignore:
      - '**/*.md'

jobs:
  nightly-build-push-latest:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 3: Set up Make
      - name: Set up Make
        run: sudo apt-get install -y make

      # Step 4: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Build the Docker image using 'make build'
      - name: Build Docker image
        run: |
          make docker-build
          docker tag kms-secp256k1-api ${{ secrets.DOCKER_USERNAME }}/kms-secp256k1-api:latest
          docker tag kms-secp256k1-api ${{ github.repository_owner }}/kms-secp256k1-api:latest
          docker tag kms-secp256k1-api verqhealth/kms-secp256k1-api:latest

      # Step 6: Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/kms-secp256k1-api:latest

      # Step 7: # Log in to GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PAT }}

      # Step 8: Push the Docker image to GHCR
      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/verqhealth/kms-secp256k1-api:latest
          docker push ghcr.io/${{ github.repository_owner }}/kms-secp256k1-api:latest
